### ISSUE TITLE
Additional projects to document

### ISSUE THREAD

**Issue by mrjoelkemp** [mrjoelkemp/awesome-paid-open-source#10]
* Sidekiq
* npm
* masonry (from metafizzy)

**Comment by uxcq** [comment]
Possibly Elementary OS for doing it wrong!

https://en.wikipedia.org/wiki/Elementary_OS#Controversy

**Comment by mrjoelkemp** [comment]
@uxcq added the associated blog post form Elementary OS: http://blog.elementary.io/post/110645528530/payments. Thanks again for sharing.
