### ISSUE TITLE
Donation website 

### ISSUE THREAD

**Issue by amanjeev** [mrjoelkemp/awesome-paid-open-source#28]
Not sure if you want to but found another donation site : https://donorbox.org/

**Comment by mrjoelkemp** [comment]
Great find. It's more of a payment platform than a donation site though. Would you be up for adding it to the list of payment platforms?

**Comment by amanjeev** [comment]
Sure. I was away for the weekend. Will do soon.

**Comment by mrjoelkemp** [comment]
Fixed via #30
