### ISSUE TITLE
Include equity compensation?

### ISSUE THREAD

**Issue by jordanh** [mrjoelkemp/awesome-paid-open-source#32]
At [our company](http://parabol.co) we've been experimenting with a new model, where we're compensating qualifying contributors with equity in our company.

We call the program [Equity for Effort](https://focus.parabol.co/equity-for-effort-v2-0-7ca93e0a3968). Would that be interesting to add to this document? Shall I offer a PR?

**Comment by rnicholus** [comment]
Interesting idea. I'm curious what a contributor can do with equity in your company. In what specific ways does this benefit or empower them?

**Comment by mrjoelkemp** [comment]
This would make a solid addition to the perspectives section. Were you thinking of another section to place this in @jordanh?

**Comment by mrjoelkemp** [comment]
Also curious about the answer to @rnicholus' question. Very interesting solution to the problem.

**Comment by jordanh** [comment]
@rnicholus: great questions! Many years ago now, Red Hat gifted Linux kernel contributors shares in the Red Hat corporation just prior to the Red Hat IPO. If accepted, these shares could then be sold on the open market. In our equity compensation program, it's our hope that our shares would gain value over time and be exchanged for cash during a liquidity event (such as an acquisition) or IPO.

There are so many individual motivations folks have for contributing to open source projects: educational, social, referencable achievements, monetary compensation... we're testing the hypothesis that there are a set of developers who are motivated by higher risk compensation. Odds are, our little company will fail and the shares will be worthless. However, if we don't fail, the shares we are exchanging for contributions could be very valuable.

At present, we're short on cash but long on equity. In the future, we anticipate changing our formula so we issue less equity and issue more cash. So, instead of offering 10,000 shares in our company (~0.10% ownership) we instead might, for example, offer 5,000 shares and $2,500 cash. Further in the future, we may only offer cash compensation like other paid open source projects.

@mrjoelkemp: ah, perspectives would be a good home for this. Thank you for the suggestion! I'll draft something up and submit the PR...

**Comment by rnicholus** [comment]
#33 has been merged. Feel free to close out this issue unless more discussion is prudent.
