### ISSUE TITLE
Add Maintainer.io

### ISSUE THREAD

**Issue by RichardLitt** [mrjoelkemp/awesome-paid-open-source#36]
I've created [Maintainer.io](https://maintainer.io) to help companies and people offload the maintenance of their open source projects. I wrote a medium article about it, [here](https://medium.com/@richlitt/oss-maintenance-as-a-service-helping-maintainers-maintain-their-code-f9717e4990ad). 

I'd like to add it to this list, but I'm unsure as to where. What do you think?

**Comment by mrjoelkemp** [comment]
Thanks for contributing @RichardLitt! 

Is it possible for folks in the community to apply to be paid maintainers for projects coming to maintainer.io?

**Comment by RichardLitt** [comment]
Thanks for the great list! 

Good question! At the moment, no. That would be nice down the road, but I'll need a few more clients before it'll be worth scaling out like that.

**Comment by mrjoelkemp** [comment]
Thanks for the clarification @RichardLitt. The purpose of the repo is to encourage devs to find ways of earning a living doing open source. I'm afraid without them being able to earn money from your service, it's more of an advertisement.

Feel free to circle back when the product more closely aligns with the goals of the repo.

Regardless, thanks for checking out the list and contributing!

**Comment by RichardLitt** [comment]
Makes sense to me! Apologies if that came off as spammy - honestly, this is a cool list. I'll let you know if I change this so that other people can make money off of it easily, as a marketplace. 

Thank you!

**Comment by mrjoelkemp** [comment]
Not spammy at all! Thanks for understanding. Best of luck with the project; the marketplace would be awesome! 

Cheers!
