### ISSUE TITLE
Synergy (Free & paid versions)

### ISSUE THREAD

**Issue by uxcq** [mrjoelkemp/awesome-paid-open-source#6]
For your list.

https://github.com/symless/synergy

https://blog.symless.com/2014/12/16/download-synergy-free/

**Comment by rnicholus** [comment]
Thanks for the suggestions! Correct me if I'm wrong @mrjoelkemp, but I think we're going for a list of perspectives, opinions, and helpful articles/resources for the OSS community (more prose than links to libraries).

**Comment by mrjoelkemp** [comment]
Thanks for contributing @uxcq!

Ideally, a blog post from the founders around the topic of sustainable open source would be an immediate fit. 

I do think it's helpful to have example projects to look to in terms of logistics (pricing strategies, payment platform used, licenses, team makeup, repo activity).  

@rnicholus Maybe an Example Projects section could work?

**Comment by rnicholus** [comment]
Now that I've looked at the two links a bit more, I _do_ think this is an awesome example for the repo. Synergy provides free access to old versions, and expects a payment for the most recent version(s). That post was written in 2014. I wonder if @nbolton has some more insight or updates regarding this model. I bet that would be interesting to hear.

These types of examples can perhaps be included in a new "projects" section. I see an article explaining the model followed by a link to the project. How does that sound?

**Comment by mrjoelkemp** [comment]
Sounds good. @rnicholus up for making the addition and then closing this issue?

**Comment by rnicholus** [comment]
Yep, I'll tackle that tonight.

**Comment by rnicholus** [comment]
I created a PR. After looking into Synergy a bit more, I found that the article in this issue description is a bit old. Instead, Synergy seems to have adopted a model almost identical to the initial one I used for Fine Uploader - keep the library open source and freely available via GitHub, but put up a pay wall for the convenience of downloading a binary. When I created the entry for Synergy in the new "Example Projects" section, I highlighted their approach, which I think is interesting and a good one for other projects to consider.

@mrjoelkemp Take a peek at my PR, we can merge it in if this looks good.

**Comment by nbolton** [comment]
Hey, let me know if you have any questions 
--
Nick BoltonCEO of SymlessSynergy Team


🇬🇧Now hiring in the UK!symless.com/careers
Symless is the company behind Synergy, keyboard and mouse sharing software.
Making the world more seamless!






On Wed, Aug 10, 2016 4:57 PM, Ray Nicholus notifications@github.com
wrote:
Now that I've looked at the two links a bit more, I do  think this is an awesome
example for the repo. Synergy provides free access to old versions, and expects
a payment for the most recent version(s). That post was written in 2014. I
wonder if @nbolton  has some more insight or updates regarding this model. I bet
that would be interesting to hear.

These types of examples can perhaps be included in a new "projects" section. I
see an article explaining the model followed by a link to the project. How does
that sound?

**Comment by Nakilon** [comment]
Link is broken and the synergy's README on github does not say how to compile for Windows. I want to use Macbook beyboard to control Windows desktop.
